/* Create the tables */

/* Drop any existing tables to allow this file to be reimported as needed */
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS Sequences;
DROP TABLE IF EXISTS Reagents;
DROP TABLE IF EXISTS Components;
DROP TABLE IF EXISTS SystemLog;
DROP TABLE IF EXISTS RunLog;

CREATE TABLE Users
(
    UserID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Username VARCHAR(30) NOT NULL,
    Password VARCHAR(30) NOT NULL,
    FirstName VARCHAR(20) NOT NULL,
    LastName VARCHAR(20) NOT NULL,
    RoleID INT UNSIGNED NOT NULL,
    ClientState VARCHAR(64) NOT NULL,
    PRIMARY KEY (UserID),
    UNIQUE KEY (Username)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE Roles
(
    RoleID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    RoleName VARCHAR(30) NOT NULL,
    Flags int unsigned NOT NULL,
    PRIMARY KEY (RoleID),
    UNIQUE KEY (RoleName)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE Sequences
(
    SequenceID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(64) NOT NULL,
    Comment VARCHAR(255),
    CreationDate TIMESTAMP DEFAULT NOW(),
    UserID INT UNSIGNED NOT NULL,
    FirstComponentID INT UNSIGNED NOT NULL,
    PRIMARY KEY (SequenceID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE Reagents
(
    ReagentID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    SequenceID INT UNSIGNED NOT NULL,
    ComponentID INT UNSIGNED NOT NULL,
    Position VARCHAR(2) NOT NULL,
    Available BOOL NOT NULL,
    Name VARCHAR(64) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    PRIMARY KEY (ReagentID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE Components
(
    ComponentID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    SequenceID INT UNSIGNED NOT NULL,
    NextComponentID INT UNSIGNED NOT NULL,
    Type VARCHAR(20) NOT NULL,
    Name VARCHAR(20),
    Details VARCHAR(2048) NOT NULL,
    PRIMARY KEY (ComponentID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE SystemLog
(
    LogID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Date TIMESTAMP DEFAULT NOW(),
    Level INT UNSIGNED NOT NULL,
    Message VARCHAR(1024) NOT NULL,
    PRIMARY KEY (LogID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE RunLog
(
    LogID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Date TIMESTAMP DEFAULT NOW(),
    Level INT UNSIGNED NOT NULL,
    UserID INT UNSIGNED NOT NULL,
    SequenceID INT UNSIGNED NOT NULL,
    ComponentID INT UNSIGNED,
    Message VARCHAR(1024) NOT NULL,
    PRIMARY KEY (LogID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

