#!/bin/bash
#
# ElixysCoreServer        Startup script for the Elixys core server
#
# chkconfig: - 85 15
# description: Starts and stops the Elixys core server
#
### BEGIN INIT INFO
# Provides: ElixysCoreServer
# Required-Start: $network
# Required-Stop:
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Short-Description: start and stop Elixys core server
# Description: The Elixys core server communicates directly with the hardware
#  and performs sequence runs.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

coreserver=${CORESERVER-python /opt/elixys/core/CoreServer.py}
pidfile=${PIDFILE-/var/run/ElixysCoreServer.pid}
lockfile=${LOCKFILE-/var/lock/ElixysCoreServer}
RETVAL=0

start() {
        echo -n $"Starting Elixys core server: "
        ${coreserver} start ${pidfile}
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch ${lockfile}
        return $RETVAL
}

stop() {
	echo -n $"Stopping Elixys core server: "
        ${coreserver} stop ${pidfile}
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  status)
        status -p ${pidfile} ElixysCoreServer
	RETVAL=$?
	;;
  *)
	echo $"Usage: service ElixysCoreServer {start|stop|restart|status}"
	RETVAL=2
esac

exit $RETVAL

