#!/bin/bash
#
# ElixysValidation        Startup script for the Elixys sequence validation daemon
#
# chkconfig: - 85 15
# description: Starts and stops the Elixys sequence validation daemon
#
### BEGIN INIT INFO
# Provides: ElixysValidation
# Required-Start: $network
# Required-Stop:
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Short-Description: start and stop Elixys sequence validation daemon
# Description: The Elixys sequence validation thread scans the database for sequences
#   in need of vaidation.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

validation=${VALIDATION-python /opt/elixys/core/SequenceValidation.py}
pidfile=${PIDFILE-/var/run/ElixysValidation.pid}
lockfile=${LOCKFILE-/var/lock/ElixysValidation}
RETVAL=0

start() {
        echo -n $"Starting Elixys sequence validation daemon: "
        ${validation} start ${pidfile}
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch ${lockfile}
        return $RETVAL
}

stop() {
	echo -n $"Stopping Elixys sequence validation daemon: "
        ${validation} stop ${pidfile}
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  status)
        status -p ${pidfile} ElixysFakePLC
	RETVAL=$?
	;;
  *)
	echo $"Usage: service ElixysValidation {start|stop|restart|status}"
	RETVAL=2
esac

exit $RETVAL

