#!/bin/bash
#
# rtmpd        Startup script for rtmpd as used by the Elixys system
#
# chkconfig: - 85 15
# description: Starts and stops the rtmpd server for the Elixys system
#
### BEGIN INIT INFO
# Provides: ElixysRtmpd
# Required-Start: $network
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop rtmpd for Elixys
# Description: The rtmpd open souce media package is used by the Elixys
#  server to stream video.
### END INIT INFO


rtmpd="python /opt/elixys/rtmpd/RtmpdDaemon.py"
pidfile=/var/run/ElixysRtmpd.pid
lockfile=/var/lock/ElixysRtmpd
RETVAL=0

start() {
        echo -n $"Starting rtmpd for Elixys: "
        ${rtmpd} start ${pidfile}
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch ${lockfile}
        return $RETVAL
}

stop() {
	echo -n $"Stopping rtmpd for Elixys: "
        ${rtmpd} stop ${pidfile}
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  status)
        status -p ${pidfile} ElixysRtmpd
	RETVAL=$?
	;;
  *)
	echo $"Usage: service ElixysRtmpd {start|stop|restart|status}"
	RETVAL=2
esac

exit $RETVAL

